### ISSUE TITLE
Instructions are not sent correctly

### ISSUE THREAD

**Issue by egzumer** [0xJoey/Arduino_93C46#4]
There is a serious bug in your code. For reading 16bit organization structure you assume there are 8 bits used for opcode + address together. This is incorrect, there are 2 bits of opcode and 8 bits of address (10 total). First bit of address is ignored by the chip but it still needs to be sent, the ignored bit is marked "X" in the documentation.

This error exists in other (all?) functions too.

**Comment by 0xJoey** [comment]
Hey, I've read your message before and forgot to reply at that time, my apologies. If you've fixed the bug, feel free to open a pull request. In any way, I'll look into this bug this week when I've got some free time.

**Comment by 0xJoey** [comment]
Merged it!
